<?php
/**
 * Hype HR Management — PHP Backend Configuration
 * Auto-generated by install.php — DO NOT edit manually.
 * Re-run install.php to change settings.
 *
 * @author  David
 * @org     Nexuzy Lab
 * @email   nexuzylab@gmail.com
 * @github  https://github.com/david0154
 * @project Hype HR Management System
 */

// ── Load SMTP config from json if available ───────────────────────────────────
$_smtpCfgFile = __DIR__ . '/smtp_config.json';
$_smsCfgFile  = __DIR__ . '/sms_config.json';
$_smtpCfg     = file_exists($_smtpCfgFile) ? (json_decode(file_get_contents($_smtpCfgFile), true) ?: []) : [];
$_smsCfg      = file_exists($_smsCfgFile)  ? (json_decode(file_get_contents($_smsCfgFile),  true) ?: []) : [];

// ── Firebase ──────────────────────────────────────────────────────────────────
define('FIREBASE_PROJECT_ID',      getenv('FIREBASE_PROJECT_ID')      ?: 'hype-hr-default');
define('FIREBASE_API_KEY',         getenv('FIREBASE_API_KEY')         ?: '');
define('FIREBASE_STORAGE_BUCKET',  getenv('FIREBASE_STORAGE_BUCKET')  ?: 'hype-hr-default.appspot.com');
define('SERVICE_ACCOUNT_PATH',     __DIR__ . '/serviceAccountKey.json');

// ── Paths ─────────────────────────────────────────────────────────────────────
define('PDF_TEMP_DIR',    __DIR__ . '/temp/');
define('ASSETS_DIR',      __DIR__ . '/../assets/');

// ── Salary slip retention (months) ───────────────────────────────────────────
define('SLIP_RETENTION_MONTHS', 12);

// ── App meta ──────────────────────────────────────────────────────────────────
define('APP_NAME',    'Hype HR Management');
define('SUPPORT_MAIL','nexuzylab@gmail.com');
define('DEV_NAME',    'David');
define('DEV_GITHUB',  'https://github.com/david0154');

// ── SMS Provider (from sms_config.json or env) ────────────────────────────────
define('SMS_PROVIDER',    $_smsCfg['sms_provider']    ?? getenv('SMS_PROVIDER')    ?: '');
define('SMS_API_KEY',     $_smsCfg['sms_api_key']     ?? getenv('SMS_API_KEY')     ?: '');
define('SMS_AUTH_TOKEN',  $_smsCfg['sms_auth_token']  ?? getenv('SMS_AUTH_TOKEN')  ?: '');
define('SMS_ACCOUNT_SID', $_smsCfg['sms_account_sid'] ?? getenv('SMS_ACCOUNT_SID') ?: '');
define('SMS_FROM_NUMBER', $_smsCfg['sms_from_number'] ?? getenv('SMS_FROM_NUMBER') ?: '');
define('SMS_SENDER_ID',   $_smsCfg['sms_sender_id']   ?? getenv('SMS_SENDER_ID')   ?: 'HYPEHR');

// ── SMTP (from smtp_config.json — loaded at runtime in mailer.php) ────────────
function getSmtpConfig(): array {
    static $cfg = null;
    if ($cfg !== null) return $cfg;
    $file = __DIR__ . '/smtp_config.json';
    $cfg = file_exists($file) ? (json_decode(file_get_contents($file), true) ?: []) : [];
    return $cfg;
}

// ── Ensure temp dir ───────────────────────────────────────────────────────────
if (!is_dir(PDF_TEMP_DIR)) mkdir(PDF_TEMP_DIR, 0755, true);
