<?php
/**
 * salary_generator.php
 * Builds the salary slip PDF using FPDF.
 *
 * Bonus line is HIDDEN on non-March slips.
 * Bonus line is shown on March slip ONLY when bonus_eligible = true.
 */

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/salary_calculator.php';

use Fpdf\Fpdf;

class SalarySlipPDF extends Fpdf
{
    private array $company;

    public function setCompany(array $company): void
    {
        $this->company = $company;
    }

    public function Header(): void
    {
        $c = $this->company;
        $this->SetFont('Arial', 'B', 14);
        $this->Cell(0, 8, strtoupper($c['name'] ?? 'COMPANY NAME'), 0, 1, 'C');
        $this->SetFont('Arial', '', 9);
        $this->Cell(0, 5, $c['address'] ?? '', 0, 1, 'C');
        $this->Cell(0, 5,
            'Email: ' . ($c['email'] ?? '') . '  |  Ph: ' . ($c['phone'] ?? ''),
            0, 1, 'C'
        );
        $this->SetDrawColor(0, 0, 0);
        $this->Line(10, $this->GetY() + 2, 200, $this->GetY() + 2);
        $this->Ln(5);
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 8, 'SALARY SLIP', 0, 1, 'C');
        $this->Ln(2);
    }

    public function Footer(): void
    {
        $this->SetY(-20);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 5,
            'Generated by Hype HR Management | ' . ($this->company['name'] ?? ''),
            0, 1, 'C'
        );
    }
}


/**
 * Generate a salary slip PDF and return the file path.
 *
 * @param array  $salary    result from calculateSalary()
 * @param array  $company   company details from Firestore settings/company
 * @param string $temp_dir  directory to save temp PDF
 * @return string  absolute path to generated PDF
 */
function generateSalarySlipPDF(array $salary, array $company, string $temp_dir = __DIR__ . '/temp'): string
{
    $month_name = date('F', mktime(0, 0, 0, $salary['month'], 1));
    $year       = $salary['year'];

    $pdf = new SalarySlipPDF('P', 'mm', 'A4');
    $pdf->setCompany($company);
    $pdf->AddPage();

    // Employee info
    $pdf->SetFont('Arial', '', 10);
    _row($pdf, 'Employee', $salary['name'],      'ID', $salary['employee_id']);
    _row($pdf, 'Month',    "$month_name $year",  '',   '');
    _divider($pdf);

    // Attendance
    $pdf->SetFont('Arial', 'B', 10);
    $pdf->Cell(0, 6, 'ATTENDANCE', 0, 1);
    $pdf->SetFont('Arial', '', 10);
    _line($pdf, 'Present Days',   $salary['full_days']);
    _line($pdf, 'Half Days',      $salary['half_days']);
    _line($pdf, 'Absent Days',    $salary['absent_days']);
    _line($pdf, 'Paid Holidays',  $salary['paid_holidays'] . '  (Sunday rule)');

    // OT
    $ot_desc = '';
    if ($salary['ot_full_days'] > 0) $ot_desc .= $salary['ot_full_days'] . ' Full';
    if ($salary['ot_half_days'] > 0) $ot_desc .= ($ot_desc ? ' + ' : '') . $salary['ot_half_days'] . ' Half';
    $ot_desc .= ' (' . $salary['ot_day_units'] . ' units)';
    _line($pdf, 'OT', $ot_desc ?: 'None');
    _divider($pdf);

    // Earnings
    $pdf->SetFont('Arial', 'B', 10);
    $pdf->Cell(0, 6, 'EARNINGS', 0, 1);
    $pdf->SetFont('Arial', '', 10);
    _money($pdf, 'Base Salary',    $salary['base_salary']);
    _money($pdf, 'Attendance Sal', $salary['attendance_salary']);
    _money($pdf, 'Overtime Pay',   $salary['ot_pay']);

    // ── Bonus: only show on March slip when eligible ──────────────────────
    if ($salary['month'] === 3 && $salary['bonus_eligible'] && $salary['annual_bonus'] > 0) {
        $prev_year = $year - 1;
        _money($pdf, 'Annual Bonus',
            $salary['annual_bonus'],
            "(1 month salary - absent cuts | eligible prev year $prev_year)"
        );
    }
    // ─────────────────────────────────────────────────────────────────────

    _divider($pdf);

    // Deductions
    $pdf->SetFont('Arial', 'B', 10);
    $pdf->Cell(0, 6, 'DEDUCTIONS', 0, 1);
    $pdf->SetFont('Arial', '', 10);
    _money($pdf, 'Advance Deduct', $salary['advance']);
    _divider($pdf);

    // Final
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->Cell(95, 8, 'FINAL SALARY', 0, 0);
    $pdf->Cell(0,  8, 'Rs. ' . number_format($salary['final_salary'], 2), 0, 1, 'R');
    _divider($pdf);

    $pdf->SetFont('Arial', '', 10);
    _line($pdf, 'Payment Mode', $salary['payment_mode']);
    $pdf->Ln(10);
    $pdf->Cell(0, 6, 'Authorized Signature', 0, 1, 'R');

    // Save
    if (!is_dir($temp_dir)) mkdir($temp_dir, 0755, true);
    $filename = $temp_dir . '/salary_'
        . $salary['employee_id'] . '_'
        . $year . '_' . str_pad($salary['month'], 2, '0', STR_PAD_LEFT)
        . '.pdf';
    $pdf->Output('F', $filename);
    return $filename;
}


// ── Helper functions ──────────────────────────────────────────────────────────
function _row(Fpdf $pdf, string $l1, string $v1, string $l2, string $v2): void
{
    $pdf->Cell(30, 6, $l1 . ':', 0, 0);
    $pdf->Cell(75, 6, $v1, 0, 0);
    if ($l2) {
        $pdf->Cell(25, 6, $l2 . ':', 0, 0);
        $pdf->Cell(0,  6, $v2, 0, 1);
    } else {
        $pdf->Ln();
    }
}

function _line(Fpdf $pdf, string $label, $value): void
{
    $pdf->Cell(60, 6, $label, 0, 0);
    $pdf->Cell(0, 6, (string) $value, 0, 1);
}

function _money(Fpdf $pdf, string $label, float $amount, string $note = ''): void
{
    $pdf->Cell(60, 6, $label, 0, 0);
    $pdf->Cell(40, 6, 'Rs. ' . number_format($amount, 2), 0, 0, 'R');
    if ($note) {
        $pdf->SetFont('Arial', 'I', 8);
        $pdf->Cell(0, 6, '  ' . $note, 0, 1);
        $pdf->SetFont('Arial', '', 10);
    } else {
        $pdf->Ln();
    }
}

function _divider(Fpdf $pdf): void
{
    $pdf->Ln(2);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(3);
}
