"""
Hype HR Management — Salary Slip PDF Generator
Generates salary slip PDF using FPDF2.
FIXED: Company name + address shown in slip header and body.
Developed by David | Nexuzy Lab | nexuzylab@gmail.com
"""

import os
from datetime import datetime

try:
    from fpdf import FPDF
except ImportError:
    raise ImportError("Install fpdf2: pip install fpdf2")


class SalarySlipPDF(FPDF):
    """
    Full salary slip with:
    - Company name + address in header
    - Employee info block
    - Attendance summary
    - Earnings / Deductions table
    - Final salary
    - Payment mode + authorized signature
    - Footer with developer credit
    """

    def header(self):
        # No auto header — we draw it manually in generate()
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 6,
            "Generated by Hype HR Management | Developed by David | Nexuzy Lab | nexuzylab@gmail.com",
            align="C")


def generate_salary_slip_pdf(
    employee: dict,
    salary_data: dict,
    company: dict,
    output_path: str,
) -> str:
    """
    Generate a full salary slip PDF.

    Args:
        employee:    Firestore employee document as dict
        salary_data: Computed salary dict with all fields
        company:     Company settings dict (name, address, email, etc.)
        output_path: Full file path to save the PDF

    Returns:
        output_path on success
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    pdf = SalarySlipPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(15, 10, 15)

    # ── Colours ───────────────────────────────────────────────────────────────
    DARK  = (13, 27, 42)      # #0d1b2a
    ORANGE = (247, 127, 0)    # #f77f00
    GREEN  = (46, 139, 87)    # #2e8b57
    LIGHT  = (255, 255, 255)
    GRAY   = (224, 224, 224)
    MUTED  = (138, 180, 200)

    # ── Company data ──────────────────────────────────────────────────────────
    comp_name    = company.get("name", "Hype Pvt Ltd")
    comp_address = company.get("address", "")
    comp_email   = company.get("email", "")
    comp_phone   = company.get("phone", "")

    # ── Employee data ─────────────────────────────────────────────────────────
    emp_name  = employee.get("name", "")
    emp_id    = employee.get("employee_id", "")
    emp_email = employee.get("email", "")
    emp_mob   = employee.get("mobile", "")
    emp_pan   = employee.get("pan", "")

    # ── Salary data ───────────────────────────────────────────────────────────
    month         = salary_data.get("month", "")
    year          = salary_data.get("year", str(datetime.now().year))
    base_salary   = float(salary_data.get("base_salary", 0))
    att_salary    = float(salary_data.get("attendance_salary", 0))
    ot_pay        = float(salary_data.get("ot_pay", 0))
    bonus         = float(salary_data.get("bonus", 0))
    deduction     = float(salary_data.get("deduction", 0))
    advance       = float(salary_data.get("advance", 0))
    final_salary  = float(salary_data.get("final_salary", 0))
    payment_mode  = salary_data.get("payment_mode", "CASH")
    total_present = salary_data.get("total_present", 0)
    half_days     = salary_data.get("half_days", 0)
    absent_days   = salary_data.get("absent_days", 0)
    paid_holidays = salary_data.get("paid_holidays", 0)
    ot_hours      = salary_data.get("ot_hours", 0)
    working_days  = salary_data.get("working_days", 26)

    # ══════════════════════════════════════════════════════════════════════════
    # HEADER — Company name + address
    # ══════════════════════════════════════════════════════════════════════════
    pdf.set_fill_color(*DARK)
    pdf.rect(0, 0, 210, 38, "F")

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*ORANGE)
    pdf.set_xy(15, 7)
    pdf.cell(120, 10, comp_name, align="L")

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*MUTED)
    pdf.set_xy(15, 18)
    if comp_address:
        pdf.cell(130, 5, comp_address, align="L")
        pdf.set_xy(15, 23)
    addr_line2 = " | ".join(filter(None, [comp_email, comp_phone]))
    if addr_line2:
        pdf.cell(130, 5, addr_line2, align="L")

    # Salary slip label on right
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*LIGHT)
    pdf.set_xy(140, 10)
    pdf.cell(55, 8, "SALARY SLIP", align="R")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*MUTED)
    pdf.set_xy(140, 19)
    pdf.cell(55, 6, f"{month} {year}", align="R")

    pdf.set_y(42)

    # ══════════════════════════════════════════════════════════════════════════
    # EMPLOYEE INFO BLOCK
    # ══════════════════════════════════════════════════════════════════════════
    pdf.set_fill_color(22, 36, 54)  # #162436
    pdf.set_draw_color(*DARK)
    pdf.set_text_color(*GRAY)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(22, 36, 54)
    pdf.cell(0, 7, "", ln=True)

    # Two-column employee info
    info_left = [
        ("Employee Name", emp_name),
        ("Employee ID",   emp_id),
        ("Mobile",        emp_mob),
    ]
    info_right = [
        ("Email",  emp_email or "—"),
        ("PAN",    emp_pan or "—"),
        ("Company", comp_name),
    ]

    col_w = 90
    for (lk, lv), (rk, rv) in zip(info_left, info_right):
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*MUTED)
        pdf.cell(32, 7, lk + ":", align="R")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(col_w - 32, 7, lv)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*MUTED)
        pdf.cell(32, 7, rk + ":", align="R")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(0, 7, rv, ln=True)

    # Orange separator
    pdf.set_draw_color(*ORANGE)
    pdf.set_line_width(0.5)
    y = pdf.get_y() + 2
    pdf.line(15, y, 195, y)
    pdf.set_y(y + 4)

    # ══════════════════════════════════════════════════════════════════════════
    # ATTENDANCE SUMMARY
    # ══════════════════════════════════════════════════════════════════════════
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*ORANGE)
    pdf.cell(0, 7, "ATTENDANCE SUMMARY", ln=True)
    pdf.set_y(pdf.get_y() + 1)

    att_cols = [
        ("Working Days",    working_days),
        ("Present Days",    total_present),
        ("Half Days",       half_days),
        ("Absent Days",     absent_days),
        ("Paid Holidays",   paid_holidays),
        ("OT Hours",        f"{ot_hours} hrs"),
    ]
    col_w2 = 30
    label_w = 30
    for i, (label, val) in enumerate(att_cols):
        if i % 3 == 0 and i != 0:
            pdf.ln(7)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*MUTED)
        pdf.cell(label_w, 6, label + ":")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(col_w2, 6, str(val))
    pdf.ln(10)

    # Orange separator
    y = pdf.get_y()
    pdf.set_draw_color(*ORANGE)
    pdf.line(15, y, 195, y)
    pdf.set_y(y + 4)

    # ══════════════════════════════════════════════════════════════════════════
    # EARNINGS / DEDUCTIONS TABLE
    # ══════════════════════════════════════════════════════════════════════════
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*ORANGE)
    pdf.cell(90, 7, "EARNINGS", align="C")
    pdf.cell(90, 7, "DEDUCTIONS", align="C", ln=True)
    pdf.set_y(pdf.get_y() + 1)

    # Table header
    pdf.set_fill_color(*DARK)
    pdf.set_text_color(*LIGHT)
    pdf.set_font("Helvetica", "B", 8)
    for label in ["Component", "Amount", "Component", "Amount"]:
        pdf.cell(45, 6, label, border=1, fill=True, align="C")
    pdf.ln()

    earnings = [
        ("Base Salary",       f"Rs. {base_salary:,.2f}"),
        ("Attendance Salary", f"Rs. {att_salary:,.2f}"),
        ("Overtime Pay",      f"Rs. {ot_pay:,.2f}"),
        ("Bonus",             f"Rs. {bonus:,.2f}"),
    ]
    deductions = [
        ("Deduction",   f"Rs. {deduction:,.2f}"),
        ("Advance",     f"Rs. {advance:,.2f}"),
        ("", ""),
        ("", ""),
    ]

    pdf.set_fill_color(22, 36, 54)
    pdf.set_font("Helvetica", "", 9)
    for (ek, ev), (dk, dv) in zip(earnings, deductions):
        pdf.set_text_color(*GRAY)
        pdf.cell(45, 6, ek, border=1, fill=True)
        pdf.set_text_color(*GREEN if ev else GRAY)
        pdf.cell(45, 6, ev, border=1, fill=True, align="R")
        pdf.set_text_color(*GRAY)
        pdf.cell(45, 6, dk, border=1, fill=True)
        pdf.set_text_color(200, 60, 60) if dv else pdf.set_text_color(*GRAY)
        pdf.cell(45, 6, dv, border=1, fill=True, align="R")
        pdf.ln()

    pdf.set_y(pdf.get_y() + 4)

    # ══════════════════════════════════════════════════════════════════════════
    # FINAL SALARY BOX
    # ══════════════════════════════════════════════════════════════════════════
    pdf.set_fill_color(*GREEN)
    pdf.set_text_color(*LIGHT)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 12, f"  NET SALARY:  Rs. {final_salary:,.2f}",
             fill=True, align="L", ln=True)

    pdf.set_y(pdf.get_y() + 4)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 6, f"Payment Mode: {payment_mode}", ln=True)

    # ══════════════════════════════════════════════════════════════════════════
    # SIGNATURE
    # ══════════════════════════════════════════════════════════════════════════
    pdf.set_y(pdf.get_y() + 14)
    pdf.set_draw_color(*MUTED)
    pdf.set_line_width(0.3)
    pdf.line(130, pdf.get_y(), 195, pdf.get_y())
    pdf.set_y(pdf.get_y() + 2)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*MUTED)
    pdf.set_x(130)
    pdf.cell(65, 5, "Authorized Signature", align="C")

    pdf.output(output_path)
    return output_path
