pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // FIX: required for QRGenerator (com.github.androidmads:QRGenerator)
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "HypeHR"
include ':app'
